addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.1.20")
addSbtPlugin("com.typesafe.sbt"          % "sbt-git"                   % "1.0.1")
addSbtPlugin("io.spray"                  % "sbt-revolver"              % "0.9.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager"       % "1.8.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"              % "2.4.3")